// Generates frozen conformance vectors from the built library.
// Run manually (node scripts/generate-vectors.js) ONLY when intentionally
// creating or updating vectors after a deliberate algorithm change. The
// committed vectors/equality-vectors.json is the authoritative contract; the
// test (src/__tests__/vectors.test.ts) asserts the library still reproduces it.
const fs = require('node:fs')
const path = require('node:path')
const { simhashEquality, minhashEquality } = require('../dist/simhash.js')

// Each case documents what it exercises. Keep inputs stable; their hashes are the contract.
const CASES = [
  { name: 'empty string', input: '' },
  { name: 'punctuation only (empty-path fallback)', input: '!!! ??? ...' },
  { name: 'emoji only (empty-path fallback)', input: '🎉🎉🎉' },
  { name: 'single short token (filter fallback)', input: 'gm' },
  { name: 'single short token, different case (equals gm)', input: 'GM' },
  { name: 'short greeting', input: 'good morning nostr' },
  { name: 'diacritics fold to base letters', input: 'café déjà vu naïve' },
  { name: 'diacritics stripped (equals the accented form)', input: 'cafe deja vu naive' },
  { name: 'url is replaced', input: 'check this out https://example.com/path?q=1 amazing' },
  { name: 'numbers are replaced', input: 'i bought 3 apples and 47 oranges today' },
  { name: 'mixed case + punctuation noise', input: 'The Quick, BROWN fox! Jumps... over the lazy dog?' },
  { name: 'classic pangram', input: 'the quick brown fox jumps over the lazy dog' },
  { name: 'stemming: plurals and -ing/-ed collapse', input: 'running runners watched watches cats dogs' },
  { name: 'longform article paragraph', input:
    'Researchers studying coastal erosion published a detailed survey describing how shifting sediment ' +
    'patterns reshape estuaries over decades. Their fieldwork combined satellite imagery with sediment ' +
    'cores collected from a dozen river mouths along the northern shoreline. The team argued that ' +
    'traditional models underestimate the influence of seasonal storms.' },
  { name: 'cosmetic variant of the longform paragraph (case/punctuation only, must equal)', input:
    'RESEARCHERS studying coastal erosion published a detailed survey, describing how shifting sediment ' +
    'patterns reshape estuaries over decades!!  Their fieldwork combined satellite imagery with sediment ' +
    'cores collected from a dozen river mouths along the northern shoreline... The team argued that ' +
    'traditional models underestimate the influence of seasonal storms.' },
  { name: 'unrelated longform paragraph', input:
    'Orbital weather arrays recalibrated at noon after a week of magnetosphere turbulence. Engineers ' +
    'replaced two damaged sensor packs and rerouted power through a backup lattice to stabilize data ' +
    'collection across the southern relay network during the maintenance window.' },
  { name: 'unicode mixed scripts', input: '👋 Hello 世界 Привет mundo' },
  { name: 'repeated tokens (dedup in sketch)', input: 'bitcoin bitcoin bitcoin lightning lightning network' },
  { name: 'whitespace and newlines collapse', input: '  line one\r\n\r\n   line   two\t\ttabs  ' },
]

function build(fn) {
  return CASES.map(({ name, input }) => ({ name, input, hex: fn(input).hex }))
}

const out = {
  _comment:
    'Frozen conformance vectors for simhash-ts equality fingerprints. Implementors MUST reproduce ' +
    'these exact hex outputs (see NIP-FF-3). Generated by scripts/generate-vectors.js; do not edit by hand.',
  'minhash-equality-v1': build(minhashEquality),
  'simhash-equality-v2': build(simhashEquality),
}

const dest = path.join(__dirname, '..', 'vectors', 'equality-vectors.json')
fs.mkdirSync(path.dirname(dest), { recursive: true })
fs.writeFileSync(dest, JSON.stringify(out, null, 2) + '\n')
console.log(`wrote ${out['minhash-equality-v1'].length} vectors per algorithm to ${path.relative(path.join(__dirname, '..'), dest)}`)
